INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (1, 'finden', 'finne', 'finner', 'fant', 'har funnet', 1, '2024-10-31 16:37:12');
INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (2, 'gehen', 'gå', 'går', 'gikk', 'har gått', 1, '2024-10-31 16:37:12');
INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (3, 'essen', 'spise', 'spiser', 'spiste', 'har spist', 1, '2024-10-31 16:37:12');
INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (4, 'trinken', 'drikke', 'drikker', 'drakk', 'har drukket', 1, '2024-10-31 16:37:12');
INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (5, 'sehen', 'se', 'ser', 'så', 'har sett', 0, '2024-10-31 16:37:12');
INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (6, 'kommen', 'komme', 'kommer', 'kom', 'har kommet', 1, '2024-10-31 16:37:12');
INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (7, 'machen', 'gjøre', 'gjør', 'gjorde', 'har gjort', 1, '2024-10-31 16:37:12');
INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (8, 'sprechen', 'snakke', 'snakker', 'snakket', 'har snakket', 1, '2024-10-31 16:37:12');
INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (9, 'lesen', 'lese', 'leser', 'leste', 'har lest', 0, '2024-10-31 16:37:12');
INSERT INTO `verbs` (`id`, `german`, `norsk`, `norsk_present`, `norsk_past`, `norsk_past_perfekt`, `active`, `datetime`)
VALUES (10, 'schreiben', 'skrive', 'skriver', 'skrev', 'har skrevet', 0, '2024-10-31 16:37:12');
